main page
Pavel545/an-app-with-music pull request #1
Opened 2022-09-07 16:11 UTC by Pavel545

5.2 JSX

2022-09-08 07:11 UTC, mrerberg requested changes

2022-09-08 07:11 UTC, mrerberg commented on src/Bar.js
> +function PlayerBtn(params) {
1 файл - 1 компонент

2022-09-08 07:11 UTC, mrerberg commented on src/css/style.scss
> +* {
Зачем тебе данный файл?

2022-09-08 07:11 UTC, mrerberg commented on src/css/style.css.map
> +{
Зачем тебе данный файл?

2022-09-08 07:11 UTC, mrerberg commented on src/index.js
> +        <footer className="footer"></footer>
Этот компонент пустой, смело убирай

2022-09-08 07:11 UTC, mrerberg commented on src/index.js
> +        <footer className="footer"></footer>
Точнее, у футера нет контента, можно убрать

2022-09-08 08:55 UTC, Pavel545 commented on src/Bar.js
> +function PlayerBtn(params) {
тобиш на каждую функцию свой файл?или имеется в виду большие части, а мелкие можно оставить?

2022-09-09 05:41 UTC, mrerberg commented on src/Bar.js
> +function PlayerBtn(params) {
Не на каждую функцию, а на каждый компонент. То есть если функция реализует компонент, то она должна быть 1 в файле. Функции хелперы можно оставлять, но тоже лучше выносить в свои файлики

2022-09-09 05:43 UTC, mrerberg requested changes

2022-09-09 05:43 UTC, mrerberg commented on src/Burger.js
> +function Burger() {
Вот только для компонентов принято заводить папку. 

Burger/
-- index.jsx (код компонента)
-- index.css/index.module.css/styles.js (стили)
... и все, что нужно компоненту

2022-09-11 12:31 UTC, mrerberg requested changes

2022-09-11 12:31 UTC, mrerberg commented on src/index.js
> +import Main from './Main/Main';
Именно поэтому лучше файл с компонентом как index, чтобы путь сократить

2022-09-12 08:02 UTC, merged