5.5
Pavel545/an-app-with-music pull request #4
Opened 2022-09-18 17:12 UTC by Pavel545

2022-09-19 07:06 UTC, mrerberg requested changes

2022-09-19 07:06 UTC, mrerberg commented on src/components/Main/Main.js
> +const { useState,useEffect } = React;
import { useState, useEffect } from 'react';

2022-09-19 07:06 UTC, mrerberg commented on src/routes.jsx
> +import { Routes, Route } from "react-router-dom";
А ты установил зависимости? Я не вижу изменений в package.json

2022-09-19 18:10 UTC, mrerberg requested changes

2022-09-19 18:10 UTC, mrerberg commented on src/routes.jsx
> +import App from "./App";
Аpp - все приложение целиком. MainPage?

2022-09-19 18:10 UTC, mrerberg commented on src/pages/login/index.js
> +import { NavLink } from "react-router-dom";
Некоторые папки компонентов именуются с большой буквы, где-то с маленькой. Как в итоге?

2022-09-19 18:10 UTC, mrerberg commented on src/pages/login/index.js
> +import { NavLink } from "react-router-dom";
Почему папка называется login, а компонент Authorization?

2022-09-19 18:10 UTC, mrerberg commented on src/components/Burger/Burger.js
> +import { useState} from 'react';
Что с форматированием?

2022-09-20 06:17 UTC, Pavel545 commented on src/components/Burger/Burger.js
> +import { useState} from 'react';
а вот этот вопрос я не понял

2022-09-20 06:18 UTC, Pavel545 commented on src/pages/login/index.js
> +import { NavLink } from "react-router-dom";
я сначала хотел логин назвать но подумал что как то размывчато звучит, переименовал, а папку то и не вспомнил

2022-09-20 06:20 UTC, Pavel545 commented on src/routes.jsx
> +import App from "./App";
ээээто не знаю как назвать, наверно лучше обозвать greeterUser и запихнуть в страниц, а авторизацию в компоненты?

2022-09-20 06:22 UTC, Pavel545 commented on src/routes.jsx
> +import { Routes, Route } from "react-router-dom";
а вот как исправилось непонял, всё устанавливал не работало, а как на след день запустил, всё работает...

2022-09-21 06:05 UTC, mrerberg commented on src/routes.jsx
> +import App from "./App";
Я тебе подсказал, как назвать. MainPage

2022-09-21 06:06 UTC, mrerberg commented on src/components/Burger/Burger.js
> +import { useState} from 'react';
{ useState}

Не используешь perttier?

2022-09-21 06:07 UTC, mrerberg requested changes

2022-09-21 06:07 UTC, mrerberg commented on src/routes.jsx
> +import App from "./GreeterUser ";
Что за пробел в пути до файла?

2022-09-21 06:07 UTC, mrerberg commented on src/routes.jsx
> +import App from "./GreeterUser ";
Почему компонент называется App, а папка GreeterUser?

2022-09-21 08:44 UTC, Pavel545 commented on src/components/Burger/Burger.js
> +import { useState} from 'react';
не использовал..

2022-09-22 07:29 UTC, mrerberg approved these changes

2022-09-23 11:14 UTC, merged