5.6
Pavel545/an-app-with-music pull request #5
Opened 2022-09-23 11:14 UTC by Pavel545

2022-09-26 06:01 UTC, mrerberg requested changes

2022-09-26 06:01 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +        clearInterval(intervalRef.current)
Данную строку я бы вынес из этой функции, так как не очевидно, что она тут присутствует

2022-09-26 06:01 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +        clearInterval(intervalRef.current)
по названию функции можно понять, что она стартует таймер, но никак не понять, что она его и очищает

2022-09-26 08:56 UTC, Pavel545 commented on src/components/Bar/Bar.jsx
> +    const currentPercentage = duration
ту т делема, небольшая, если выносить, их, то передавать в них столько же каждый раз сколько кода в самих переменных, от этого мне кажется тока хуже

2022-09-26 09:38 UTC, Pavel545 commented on src/components/Bar/Bar.jsx
> +                    max={duration ? duration : `${duration}`}
ну ему жэ сразу число присваивается, так что наверно не будет такого чтоб крякнул он просто от того что вылез undefined

2022-09-27 05:54 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +                    max={duration ? duration : `${duration}`}
duration || 0
Или просто передать duration

Просто тернраник тут бесполезен с значением `${duration}`

2022-09-27 05:55 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +    const currentPercentage = duration
Чаго? Тебе нужно будет в функцию кинуть 1 аргумент и все

2022-09-27 05:57 UTC, mrerberg requested changes

2022-09-27 05:57 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +    // Destructure for conciseness
Зачем коммент?

2022-09-27 05:57 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +// ,
?

2022-09-27 05:57 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +const styleProgress = (trackStyling, trackProgress, duration,onScrubEnd,onScrub) => {
А это что?

2022-09-27 09:52 UTC, Pavel545 commented on src/components/Bar/Bar.jsx
> +const styleProgress = (trackStyling, trackProgress, duration,onScrubEnd,onScrub) => {
вы же рекомендовали всю стелизацию вынести в функцию

2022-09-28 05:52 UTC, mrerberg requested changes

2022-09-28 05:52 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +const styleProgress = (trackStyling, trackProgress, duration,onScrubEnd,onScrub) => {
Да, только данная функция ничего, связанного со стилями, не делает. Она просто упаковывает пропсы

2022-09-28 05:52 UTC, mrerberg commented on src/components/Bar/Bar.jsx
>          type: 'range',
А почему вдруг данное поле и многие другие попадают в ключ style у компонента BarPlayerProgress?

2022-09-28 09:26 UTC, Pavel545 commented on src/components/Bar/Bar.jsx
>          type: 'range',
кажется я понял..

2022-09-29 08:13 UTC, merged